---
# Copy configuration.
- name: Ensure vscode config dir exists
  ansible.builtin.file:
    path: ~/Library/Application\ Support/Code/User/
    state: directory
    mode: '0755'

# Copy configuration.
- name: Symlink config file into config dir
  ansible.builtin.file:
    src: ~/dotfiles/vscodesettings.json
    dest: ~/Library/Application\ Support/Code/User/settings.json
    state: link
  # mkdir -p ~/Library/Application\ Support/Code/User/
  # ln -fs ~/dotfiles/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
