---
- name: Ensure workbench  dir exists
  ansible.builtin.file:
    path: ~/_workbench
    state: directory
    mode: '0755'

- name: Ensure local bin dir exists
  ansible.builtin.file:
    path: ~/bin
    state: directory
    mode: '0755'
      
- name: Ensure local dotfiles dir exists
  ansible.builtin.file:
    path: ~/local-dotfiles
    state: directory
    mode: '0755'

- name: Touch local .path
  ansible.builtin.file:
    path: ~/local-dotfiles/.path
    state: touch
    mode: u=rw,g=r,o=r
    modification_time: preserve
    access_time: preserve

- name: Touch local .env
  ansible.builtin.file:
    path: ~/local-dotfiles/.env
    state: touch
    mode: u=rw,g=r,o=r
    modification_time: preserve
    access_time: preserve

- name: Touch local .alias
  ansible.builtin.file:
    path: ~/local-dotfiles/.alias
    state: touch
    mode: u=rw,g=r,o=r
    modification_time: preserve
    access_time: preserve

- name: Touch local Brewfile
  ansible.builtin.file:
    path: ~/local-dotfiles/Brewfile
    state: touch
    mode: u=rw,g=r,o=r
    modification_time: preserve
    access_time: preserve

- name: Copy global git ignore
  ansible.builtin.file:
    src: ~/dotfiles/.gitignore_global
    dest: ~/.gitignore
    state: link


- name: Copy global git config
  ansible.builtin.file:
    src: ~/dotfiles/.gitconfig
    dest: ~/.gitconfig
    state: link



